#!/usr/bin/env ruby -wU
#
# Takes either site name or port (for localhost) as argument.
#

class Local_IP
  require 'socket'

  def self.open_site
    ip = self.local_ip
    puts "Your IP address: #{ip}\n\n"
    in_sites_dir = Dir.pwd.split('/')[-2].downcase == "sites"
    if ARGV[0] && !in_sites_dir
      %x[open http://#{ARGV[0]}.#{ip}.xip.io:8080]
    elsif in_sites_dir
      domain = Dir.pwd.split('/')[-1]
      if ARGV[0]
        port = ":#{ARGV[0]}"
        %x[open http://#{ip}.xip.io#{port}]
      else
        port = ":8080"
        %x[open http://#{domain}.#{ip}.xip.io#{port}]
      end
    else
      %x[open http://#{ip}:8080]
    end
  end

  def self.local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1 # use system call as if connecting to google
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end

end

Local_IP.open_site
