#!/usr/bin/env ruby -wKU

class Local_IP
  require 'socket'

  def self.open_site
    ip = self.local_ip
    puts "Your IP address: #{ip}\n\n"
    if ARGV[0]
      %x[open http://#{ARGV[0]}.#{ip}.xip.io:8080]
    elsif Dir.pwd.split('/')[-2].downcase == "sites"
      domain = Dir.pwd.split('/')[-1]
      %x[open http://#{domain}.#{ip}.xip.io:8080]
    else
      %x[open http://#{ip}:8080]
    end
  end

  def self.local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1 # use system call as if connecting to google
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end

end

Local_IP.open_site
