#!/usr/bin/env ruby -wKU

class Local_IP_Opener
  require 'socket'

  def self.open_site
    ip = self.local_ip
    puts "Your IP address: #{ip}\n\n"
    %x[open http://#{ip}.xip.io]
  end

  def self.local_ip
    orig, Socket.do_not_reverse_lookup = Socket.do_not_reverse_lookup, true  # turn off reverse DNS resolution temporarily

    UDPSocket.open do |s|
      s.connect '64.233.187.99', 1 # use system call as if connecting to google
      s.addr.last
    end
  ensure
    Socket.do_not_reverse_lookup = orig
  end

end


Local_IP_Opener.open_site
