// Generated by CoffeeScript 1.3.3
var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

$("a.file").each(function() {
  var ext, filetypes, href, k, v, _results;
  filetypes = {
    pdf: ["pdf"],
    doc: ["doc", "docx"],
    xls: ["xls", "xlsx"],
    txt: ["txt"],
    zip: ["zip"]
  };
  href = $(this)[0].href;
  ext = href.match(/(?!\.)[a-zA-Z]{3,4}$/);
  if (ext) {
    ext = ext[0];
    _results = [];
    for (k in filetypes) {
      v = filetypes[k];
      if (__indexOf.call(v, ext) >= 0) {
        _results.push($(this).addClass(k));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  }
});
