#!/bin/bash

# get current working directory so tmux session can be unique
name="Basic-${PWD##*/}"
if [ $1 ]; then
  remote=$1
else
  remote="origin"
fi
# get current branch
branch_name="$(git symbolic-ref HEAD 2>/dev/null)" || branch_name="(unnamed branch)"  # detached HEAD
branch_name=${branch_name##refs/heads/}

tmux new-session -s "$name" -n bash -d
if [ "$branch_name" != "(unnamed branch)" ]; then
  tmux send-keys -t "$name" "git pull $remote master" C-m
fi
tmux send-keys -t "$name" "lip" C-m
tmux send-keys -t "$name" "ll" C-m
tmux new-window -n sassw
tmux send-keys -t "$name" "sassw" C-m
tmux new-window -n vim 'reattach-to-user-namespace vim .'
tmux attach -t "$name"
